name: Deploy to AWS CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Zip source code
      run: zip -r my-app.zip .

    - name: Upload to S3
      run: aws s3 cp my-app.zip s3://${{ secrets.S3_BUCKET }}/my-app.zip


    - name: Deploy to CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name node-cicd \
          --deployment-group-name node-cicd-dg \
          --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=my-app.zip